### ISSUE TITLE
Cannot open device 

### ISSUE THREAD

**Issue by abhishektaneja** [porsager/busylight#7]
I'm getting following error
```
Error: cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14200000/BUSYLIGHT@14200000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14200000,0
    at Error (native)
    at new HID (/Users/ataneja/localhost/git/busylight/node_modules/node-hid/nodehid.js:28:14)
    at Busylight.connect (/Users/ataneja/localhost/git/busylight/lib/busylight.js:103:19)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3
```

**Comment by porsager** [comment]
Hi :) Did you figure out what was wrong?

**Comment by abhishektaneja** [comment]
Yes, for me it happened because device was busy with another app.

**Comment by porsager** [comment]
Ah good to know :) Thank you.
